//Hooray
#include "main_app.h"
#include "FreeRTOS.h"
#include "task.h"
#include "stm32g4xx_hal.h"

extern ADC_HandleTypeDef hadc1;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim16;
extern TIM_HandleTypeDef htim17;
extern uint32_t SystemCoreClock;

volatile uint16_t joystick_dma[4]; 

void Route_TIM16_To_D15(void) {
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // Redirect TIM16_CH1 from hidden PA12 over to Arduino header D15 (PB8)
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM16; 
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

static void ConfigServoTimer(TIM_HandleTypeDef *htim) {
    uint32_t prescaler = (SystemCoreClock / 1000000) - 1;
    htim->Instance->PSC = prescaler;
    htim->Instance->ARR = 20000 - 1;
}

void TaskServoControl_J1(void *pvParameters) {
    ConfigServoTimer(&htim3);

    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);  // D12
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2);  // D9

    uint32_t pulse_x = 1500;
    uint32_t pulse_y = 1500;

    for (;;) {
        // Read directly from the background DMA buffer populated by main.c
        uint16_t j1_x = joystick_dma[0]; // A0
        uint16_t j1_y = joystick_dma[1]; // A1

        if (j1_x > 2200) pulse_x += 15; else if (j1_x < 1800) pulse_x -= 15;
        if (j1_y > 2200) pulse_y += 15; else if (j1_y < 1800) pulse_y -= 15;

        if (pulse_x > 2000) pulse_x = 2000; else if (pulse_x < 1000) pulse_x = 1000;
        if (pulse_y > 2000) pulse_y = 2000; else if (pulse_y < 1000) pulse_y = 1000;

        __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, pulse_x);
        __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, pulse_y);

        vTaskDelay(pdMS_TO_TICKS(50));
    }
}

void TaskServoControl_J2(void *pvParameters) {
    ConfigServoTimer(&htim16);
    ConfigServoTimer(&htim17);

    HAL_TIM_PWM_Start(&htim16, TIM_CHANNEL_1); // D15 (Now routed to PB8!)
    HAL_TIM_PWM_Start(&htim17, TIM_CHANNEL_1); // D11

    uint32_t pulse_x = 1500;
    uint32_t pulse_y = 1500;

    for (;;) {
        // Read directly from the background DMA buffer populated by main.c
        uint16_t j2_x = joystick_dma[2]; // A5
        uint16_t j2_y = joystick_dma[3]; // A4

        if (j2_x > 2200) pulse_x += 15; else if (j2_x < 1800) pulse_x -= 15;
        if (j2_y > 2200) pulse_y += 15; else if (j2_y < 1800) pulse_y -= 15;

        if (pulse_x > 2000) pulse_x = 2000; else if (pulse_x < 1000) pulse_x = 1000;
        if (pulse_y > 2000) pulse_y = 2000; else if (pulse_y < 1000) pulse_y = 1000;

        __HAL_TIM_SET_COMPARE(&htim16, TIM_CHANNEL_1, pulse_x);
        __HAL_TIM_SET_COMPARE(&htim17, TIM_CHANNEL_1, pulse_y);

        vTaskDelay(pdMS_TO_TICKS(50));
    }
}

void App_Main(void) {
    // Redirect TIM16_CH1 from hidden PA12 over to Arduino header D15 (PB8)
    Route_TIM16_To_D15();

    // Start background DMA using the flawless initialization generated by CubeMX in main.c
    HAL_ADC_Start_DMA(&hadc1, (uint32_t*)joystick_dma, 4);

    xTaskCreate(TaskServoControl_J1, "ServoCtrlJ1", 256, NULL, tskIDLE_PRIORITY + 2, NULL);
    xTaskCreate(TaskServoControl_J2, "ServoCtrlJ2", 256, NULL, tskIDLE_PRIORITY + 2, NULL);
}
